### ISSUE TITLE
[bug] the plugin did not colorize the link

### ISSUE THREAD

**Issue by lycoch** [Max1Truc/Firefox-add-on-for-leboncoin.fr#1]
bonjour,
65.0 (64 bits) / ubuntu 18.04
je viens d'installer le plugin, j'ai bien une icone pres de la barre d'adresse mais le lien n'est pas coloré,
j'ai l'impression que l'add on ne fonctionne plus ?

![image](https://user-images.githubusercontent.com/4572484/52472663-1e98df00-2b94-11e9-8e3b-bb367d770d55.png)

**Comment by lycoch** [comment]
les urls ont changée de modele c'est surement la source du bug exemple:

https://www.leboncoin.fr/CATEGORIE/[NUMBER].htm/

donc le manifest n'est plus a jour
    "matches": ["https://www.leboncoin.fr/*/*.htm*"],

je veux bien debugger de mon coté si vous pouvez m'indiquer comment tester depuis le Source.zip que j'ai pu compiler grace a nodejs

merci

**Comment by lycoch** [comment]
i made a pull request to fix the issue

**Comment by Max1Truc** [comment]
Bonjour @lycoch, excusez-moi de ne pas avoir répondu plus tôt, j'avoue ne pas avoir été actif récemment. 

En effet l'extension ne fonctionne plus, je vous remercie de m'avoir donné une solution directe à mon problème et je vais m'empresser de mettre à jour l'extension avec votre solution.

**Comment by Max1Truc** [comment]
L'extension ne fonctionne pas totalement avec cette solution mais je m'empresse de corriger l'erreur.

**Comment by Max1Truc** [comment]
Erreur corrigée !
