### ISSUE TITLE
Certaines catégories ne sont pas sélectionnées

### ISSUE THREAD

**Issue by jojo1992341** [Max1Truc/Firefox-add-on-for-leboncoin.fr#2]
Bonjour,
les catégories "Equipement Auto" et "Equipement Caravaning" ne sont pas sélectionnées,
on à "«Choisissez une catégorie»" et quand on choisi tout est effacé.
Merci à vous.

![Capture d’écran (57)](https://user-images.githubusercontent.com/56384580/66548309-51d7a780-eb41-11e9-8a51-d102ad559b7c.png)
![Capture d’écran (58)](https://user-images.githubusercontent.com/56384580/66548324-5a2fe280-eb41-11e9-96c3-82c191b7853f.png)

**Comment by Max1Truc** [comment]
Bonjour @jojo1992341 , excusez moi pour une réaction aussi tardive... Je vais voir ce que je peux faire.

**Comment by jojo1992341** [comment]
bonjour @Max1Truc ,
merci beaucoup et merci pour votre add-on vraiment très utile.

**Comment by Max1Truc** [comment]
Tout le plaisir est pour moi ^^

**Comment by Max1Truc** [comment]
Je tiens à préciser que ce problème sera réglé d'ici la fin des vacances.

**Comment by Max1Truc** [comment]
Le bug semble corrigé, toutefois changer la catégorie après-coup semble toujours rediriger vers la page normale pour déposer les annonces.
Merci d'avoir relevé ce bug, si vous en trouvez d'autres prévenez-moi
