### ISSUE TITLE
Non fonctionnel à présent, plus de copier-coller automatique

### ISSUE THREAD

**Issue by NyxAwroo** [Max1Truc/Firefox-add-on-for-leboncoin.fr#7]

**Comment by Max1Truc** [comment]
Je n'ai malheureusement pas le temps en ce moment de m'occuper de cette extension, qui me demande beaucoup de temps à chaque mise à jour.

Elle ne fonctionne plus pour moi non plus.

L'issue #6 reste ouverte au cas où je reprends le développement.
